<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 11 Nonlinear Relationships and Multiple Linear Regression | Data Science for Agricultural Professionals</title>
  <meta name="description" content="Practical statistics for those involved in agronomy and related agricultural sciences." />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 11 Nonlinear Relationships and Multiple Linear Regression | Data Science for Agricultural Professionals" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Practical statistics for those involved in agronomy and related agricultural sciences." />
  <meta name="github-repo" content="https://github.com/mharbur/ds-oct21c" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 11 Nonlinear Relationships and Multiple Linear Regression | Data Science for Agricultural Professionals" />
  
  <meta name="twitter:description" content="Practical statistics for those involved in agronomy and related agricultural sciences." />
  

<meta name="author" content="Marin L. Harbur" />


<meta name="date" content="2021-10-07" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="correlation-and-simple-regression.html"/>
<link rel="next" href="spatial-statistics.html"/>
<script src="libs/header-attrs-2.11/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<script src="libs/htmlwidgets-1.5.4/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.9.4.1/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.1.1/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.1.1/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-1.57.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-1.57.1/plotly-latest.min.js"></script>
<link href="libs/leaflet-1.3.1/leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-1.3.1/leaflet.js"></script>
<link href="libs/leafletfix-1.0.0/leafletfix.css" rel="stylesheet" />
<script src="libs/proj4-2.6.2/proj4.min.js"></script>
<script src="libs/Proj4Leaflet-1.0.1/proj4leaflet.js"></script>
<link href="libs/rstudio_leaflet-1.3.1/rstudio_leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-binding-2.0.4.1/leaflet.js"></script>
<script src="libs/leaflet-providers-1.9.0/leaflet-providers_1.9.0.js"></script>
<script src="libs/leaflet-providers-plugin-2.0.4.1/leaflet-providers-plugin.js"></script>
<script src="libs/stars_1f4d28-1/data_stars_starsf098bd.txt"></script>
<script src="libs/joda-0.0.1/joda.js"></script>
<script src="libs/joda-0.0.1/addImageQuery-bindings.js"></script>
<script src="libs/stars_f4bdc0-1/data_stars_starsd4cae3.txt"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Data Science for Agricultural Professionals</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#welcome"><i class="fa fa-check"></i>Welcome</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#r-language"><i class="fa fa-check"></i>R-language</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="population-statistics.html"><a href="population-statistics.html"><i class="fa fa-check"></i><b>1</b> Population Statistics</a>
<ul>
<li class="chapter" data-level="1.1" data-path="population-statistics.html"><a href="population-statistics.html#populations"><i class="fa fa-check"></i><b>1.1</b> Populations</a></li>
<li class="chapter" data-level="1.2" data-path="population-statistics.html"><a href="population-statistics.html#case-study-yield-map"><i class="fa fa-check"></i><b>1.2</b> Case Study: Yield Map</a></li>
<li class="chapter" data-level="1.3" data-path="population-statistics.html"><a href="population-statistics.html#distributions"><i class="fa fa-check"></i><b>1.3</b> Distributions</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="population-statistics.html"><a href="population-statistics.html#histograms"><i class="fa fa-check"></i><b>1.3.1</b> Histograms</a></li>
<li class="chapter" data-level="1.3.2" data-path="population-statistics.html"><a href="population-statistics.html#percentiles"><i class="fa fa-check"></i><b>1.3.2</b> Percentiles</a></li>
<li class="chapter" data-level="1.3.3" data-path="population-statistics.html"><a href="population-statistics.html#normal-distribution-model"><i class="fa fa-check"></i><b>1.3.3</b> Normal Distribution Model</a></li>
<li class="chapter" data-level="1.3.4" data-path="population-statistics.html"><a href="population-statistics.html#measures-of-center"><i class="fa fa-check"></i><b>1.3.4</b> Measures of Center</a></li>
<li class="chapter" data-level="1.3.5" data-path="population-statistics.html"><a href="population-statistics.html#measures-of-dispersion"><i class="fa fa-check"></i><b>1.3.5</b> Measures of Dispersion</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="distributions-and-probability.html"><a href="distributions-and-probability.html"><i class="fa fa-check"></i><b>2</b> Distributions and Probability</a>
<ul>
<li class="chapter" data-level="2.1" data-path="distributions-and-probability.html"><a href="distributions-and-probability.html#case-study"><i class="fa fa-check"></i><b>2.1</b> Case Study</a></li>
<li class="chapter" data-level="2.2" data-path="distributions-and-probability.html"><a href="distributions-and-probability.html#the-normal-distribution-model"><i class="fa fa-check"></i><b>2.2</b> The Normal Distribution Model</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="distributions-and-probability.html"><a href="distributions-and-probability.html#the-bell-curve"><i class="fa fa-check"></i><b>2.2.1</b> The Bell Curve</a></li>
<li class="chapter" data-level="2.2.2" data-path="distributions-and-probability.html"><a href="distributions-and-probability.html#distribution-and-probability"><i class="fa fa-check"></i><b>2.2.2</b> Distribution and Probability</a></li>
<li class="chapter" data-level="2.2.3" data-path="distributions-and-probability.html"><a href="distributions-and-probability.html#probability-and-the-normal-distribution-curve"><i class="fa fa-check"></i><b>2.2.3</b> Probability and the Normal Distribution Curve</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="distributions-and-probability.html"><a href="distributions-and-probability.html#the-z-distribution"><i class="fa fa-check"></i><b>2.3</b> The Z-Distribution</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="distributions-and-probability.html"><a href="distributions-and-probability.html#important-numbers-95-and-5"><i class="fa fa-check"></i><b>2.3.1</b> Important Numbers: 95% and 5%</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="sample-statistics.html"><a href="sample-statistics.html"><i class="fa fa-check"></i><b>3</b> Sample Statistics</a>
<ul>
<li class="chapter" data-level="3.1" data-path="sample-statistics.html"><a href="sample-statistics.html#samples"><i class="fa fa-check"></i><b>3.1</b> Samples</a></li>
<li class="chapter" data-level="3.2" data-path="sample-statistics.html"><a href="sample-statistics.html#case-study-1"><i class="fa fa-check"></i><b>3.2</b> Case Study</a></li>
<li class="chapter" data-level="3.3" data-path="sample-statistics.html"><a href="sample-statistics.html#distribution-of-sample-means"><i class="fa fa-check"></i><b>3.3</b> Distribution of Sample Means</a></li>
<li class="chapter" data-level="3.4" data-path="sample-statistics.html"><a href="sample-statistics.html#central-limit-theorem"><i class="fa fa-check"></i><b>3.4</b> Central Limit Theorem</a></li>
<li class="chapter" data-level="3.5" data-path="sample-statistics.html"><a href="sample-statistics.html#standard-error"><i class="fa fa-check"></i><b>3.5</b> Standard Error</a></li>
<li class="chapter" data-level="3.6" data-path="sample-statistics.html"><a href="sample-statistics.html#degrees-of-freedom"><i class="fa fa-check"></i><b>3.6</b> Degrees of Freedom</a></li>
<li class="chapter" data-level="3.7" data-path="sample-statistics.html"><a href="sample-statistics.html#the-t-distribution"><i class="fa fa-check"></i><b>3.7</b> The t-Distribution</a></li>
<li class="chapter" data-level="3.8" data-path="sample-statistics.html"><a href="sample-statistics.html#confidence-interval"><i class="fa fa-check"></i><b>3.8</b> Confidence Interval</a></li>
<li class="chapter" data-level="3.9" data-path="sample-statistics.html"><a href="sample-statistics.html#confidence-interval-and-probability"><i class="fa fa-check"></i><b>3.9</b> Confidence Interval and Probability</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="two-treatment-comparisons.html"><a href="two-treatment-comparisons.html"><i class="fa fa-check"></i><b>4</b> Two-Treatment Comparisons</a>
<ul>
<li class="chapter" data-level="4.1" data-path="two-treatment-comparisons.html"><a href="two-treatment-comparisons.html#side-by-side-trials"><i class="fa fa-check"></i><b>4.1</b> Side-by-Side Trials</a></li>
<li class="chapter" data-level="4.2" data-path="two-treatment-comparisons.html"><a href="two-treatment-comparisons.html#blocked-design"><i class="fa fa-check"></i><b>4.2</b> Blocked Design</a></li>
<li class="chapter" data-level="4.3" data-path="two-treatment-comparisons.html"><a href="two-treatment-comparisons.html#case-study-2"><i class="fa fa-check"></i><b>4.3</b> Case Study</a></li>
<li class="chapter" data-level="4.4" data-path="two-treatment-comparisons.html"><a href="two-treatment-comparisons.html#confidence-interval-1"><i class="fa fa-check"></i><b>4.4</b> Confidence Interval</a></li>
<li class="chapter" data-level="4.5" data-path="two-treatment-comparisons.html"><a href="two-treatment-comparisons.html#t-test"><i class="fa fa-check"></i><b>4.5</b> T-Test</a></li>
<li class="chapter" data-level="4.6" data-path="two-treatment-comparisons.html"><a href="two-treatment-comparisons.html#conclusion"><i class="fa fa-check"></i><b>4.6</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="understanding-statistical-tests.html"><a href="understanding-statistical-tests.html"><i class="fa fa-check"></i><b>5</b> Understanding Statistical Tests</a>
<ul>
<li class="chapter" data-level="5.1" data-path="understanding-statistical-tests.html"><a href="understanding-statistical-tests.html#research-question"><i class="fa fa-check"></i><b>5.1</b> Research Question</a></li>
<li class="chapter" data-level="5.2" data-path="understanding-statistical-tests.html"><a href="understanding-statistical-tests.html#the-model"><i class="fa fa-check"></i><b>5.2</b> The Model</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="understanding-statistical-tests.html"><a href="understanding-statistical-tests.html#treatment-effect"><i class="fa fa-check"></i><b>5.2.1</b> Treatment Effect</a></li>
<li class="chapter" data-level="5.2.2" data-path="understanding-statistical-tests.html"><a href="understanding-statistical-tests.html#error-effect"><i class="fa fa-check"></i><b>5.2.2</b> Error Effect</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="understanding-statistical-tests.html"><a href="understanding-statistical-tests.html#hypotheses"><i class="fa fa-check"></i><b>5.3</b> Hypotheses</a></li>
<li class="chapter" data-level="5.4" data-path="understanding-statistical-tests.html"><a href="understanding-statistical-tests.html#p-value"><i class="fa fa-check"></i><b>5.4</b> P-Value</a></li>
<li class="chapter" data-level="5.5" data-path="understanding-statistical-tests.html"><a href="understanding-statistical-tests.html#the-p-value-and-errors"><i class="fa fa-check"></i><b>5.5</b> The P-Value and Errors</a></li>
<li class="chapter" data-level="5.6" data-path="understanding-statistical-tests.html"><a href="understanding-statistical-tests.html#one-sided-vs-two-sided-hypotheses"><i class="fa fa-check"></i><b>5.6</b> One-Sided vs Two-Sided Hypotheses</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="multiple-treatment-trials.html"><a href="multiple-treatment-trials.html"><i class="fa fa-check"></i><b>6</b> Multiple Treatment Trials</a>
<ul>
<li class="chapter" data-level="6.1" data-path="multiple-treatment-trials.html"><a href="multiple-treatment-trials.html#case-study-3"><i class="fa fa-check"></i><b>6.1</b> Case Study</a></li>
<li class="chapter" data-level="6.2" data-path="multiple-treatment-trials.html"><a href="multiple-treatment-trials.html#the-linear-additive-model"><i class="fa fa-check"></i><b>6.2</b> The Linear Additive Model</a></li>
<li class="chapter" data-level="6.3" data-path="multiple-treatment-trials.html"><a href="multiple-treatment-trials.html#analysis-of-variance"><i class="fa fa-check"></i><b>6.3</b> Analysis of Variance</a></li>
<li class="chapter" data-level="6.4" data-path="multiple-treatment-trials.html"><a href="multiple-treatment-trials.html#the-f-statistic"><i class="fa fa-check"></i><b>6.4</b> The F statistic</a></li>
<li class="chapter" data-level="6.5" data-path="multiple-treatment-trials.html"><a href="multiple-treatment-trials.html#the-anova-table"><i class="fa fa-check"></i><b>6.5</b> The ANOVA Table</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="multiple-treatment-trials.html"><a href="multiple-treatment-trials.html#source-of-variation"><i class="fa fa-check"></i><b>6.5.1</b> Source of Variation</a></li>
<li class="chapter" data-level="6.5.2" data-path="multiple-treatment-trials.html"><a href="multiple-treatment-trials.html#sum-of-squares-1"><i class="fa fa-check"></i><b>6.5.2</b> Sum of Squares</a></li>
<li class="chapter" data-level="6.5.3" data-path="multiple-treatment-trials.html"><a href="multiple-treatment-trials.html#degrees-of-freedom-1"><i class="fa fa-check"></i><b>6.5.3</b> Degrees of Freedom</a></li>
<li class="chapter" data-level="6.5.4" data-path="multiple-treatment-trials.html"><a href="multiple-treatment-trials.html#mean-square"><i class="fa fa-check"></i><b>6.5.4</b> Mean Square</a></li>
<li class="chapter" data-level="6.5.5" data-path="multiple-treatment-trials.html"><a href="multiple-treatment-trials.html#f-value"><i class="fa fa-check"></i><b>6.5.5</b> F-Value</a></li>
<li class="chapter" data-level="6.5.6" data-path="multiple-treatment-trials.html"><a href="multiple-treatment-trials.html#p-value-1"><i class="fa fa-check"></i><b>6.5.6</b> P-value</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="multiple-treatment-trials.html"><a href="multiple-treatment-trials.html#visualizing-how-the-anova-table-relates-to-variance"><i class="fa fa-check"></i><b>6.6</b> Visualizing How the Anova Table Relates to Variance</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html"><i class="fa fa-check"></i><b>7</b> Multiple Treatment Designs</a>
<ul>
<li class="chapter" data-level="7.1" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#randomized-complete-block-design"><i class="fa fa-check"></i><b>7.1</b> Randomized Complete Block Design</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#case-study-randomized-complete-block-design"><i class="fa fa-check"></i><b>7.1.1</b> Case Study: Randomized Complete Block Design</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#factorial-design"><i class="fa fa-check"></i><b>7.2</b> Factorial Design</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#case-study-1-1"><i class="fa fa-check"></i><b>7.2.1</b> Case Study 1</a></li>
<li class="chapter" data-level="7.2.2" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#case-study-2-1"><i class="fa fa-check"></i><b>7.2.2</b> Case Study 2</a></li>
<li class="chapter" data-level="7.2.3" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#discussing-interactions"><i class="fa fa-check"></i><b>7.2.3</b> Discussing Interactions</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#split-plot-design"><i class="fa fa-check"></i><b>7.3</b> Split-Plot Design</a></li>
<li class="chapter" data-level="7.4" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#linear-additive-model-3"><i class="fa fa-check"></i><b>7.4</b> Linear Additive Model</a></li>
<li class="chapter" data-level="7.5" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#conclusion-1"><i class="fa fa-check"></i><b>7.5</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html"><i class="fa fa-check"></i><b>8</b> Means Separation and Data Presentation</a>
<ul>
<li class="chapter" data-level="8.1" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#case-study-4"><i class="fa fa-check"></i><b>8.1</b> Case Study</a></li>
<li class="chapter" data-level="8.2" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#least-significant-difference"><i class="fa fa-check"></i><b>8.2</b> Least Significant Difference</a></li>
<li class="chapter" data-level="8.3" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#lsd-output-in-r"><i class="fa fa-check"></i><b>8.3</b> LSD Output in R</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#statistics-table"><i class="fa fa-check"></i><b>8.3.1</b> Statistics Table</a></li>
<li class="chapter" data-level="8.3.2" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#means-table"><i class="fa fa-check"></i><b>8.3.2</b> Means Table</a></li>
<li class="chapter" data-level="8.3.3" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#groups-table"><i class="fa fa-check"></i><b>8.3.3</b> Groups Table</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#comparisonwise-versus-experimentwise-error"><i class="fa fa-check"></i><b>8.4</b> Comparisonwise versus Experimentwise Error</a></li>
<li class="chapter" data-level="8.5" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#tukeys-honest-significant-difference"><i class="fa fa-check"></i><b>8.5</b> Tukey’s Honest Significant Difference</a></li>
<li class="chapter" data-level="8.6" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#linear-contrast"><i class="fa fa-check"></i><b>8.6</b> Linear Contrast</a>
<ul>
<li class="chapter" data-level="8.6.1" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#coefficients"><i class="fa fa-check"></i><b>8.6.1</b> Coefficients</a></li>
<li class="chapter" data-level="8.6.2" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#linear-contrasts-with-r"><i class="fa fa-check"></i><b>8.6.2</b> Linear Contrasts with R</a></li>
</ul></li>
<li class="chapter" data-level="8.7" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#means-presentation"><i class="fa fa-check"></i><b>8.7</b> Means Presentation</a>
<ul>
<li class="chapter" data-level="8.7.1" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#means-tables"><i class="fa fa-check"></i><b>8.7.1</b> Means Tables</a></li>
<li class="chapter" data-level="8.7.2" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#plotting-means"><i class="fa fa-check"></i><b>8.7.2</b> Plotting Means</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html"><i class="fa fa-check"></i><b>9</b> Messy and Missing Data</a>
<ul>
<li class="chapter" data-level="9.1" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#inspecting-data-for-normal-distributions"><i class="fa fa-check"></i><b>9.1</b> Inspecting data for Normal Distributions</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#histograms-1"><i class="fa fa-check"></i><b>9.1.1</b> Histograms</a></li>
<li class="chapter" data-level="9.1.2" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#rank-percentile-plots"><i class="fa fa-check"></i><b>9.1.2</b> Rank Percentile Plots</a></li>
<li class="chapter" data-level="9.1.3" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#box-plots"><i class="fa fa-check"></i><b>9.1.3</b> Box Plots</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#inspecting-data-for-equal-variances"><i class="fa fa-check"></i><b>9.2</b> Inspecting Data for Equal Variances</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#mean-variance-plot"><i class="fa fa-check"></i><b>9.2.1</b> Mean-Variance Plot</a></li>
<li class="chapter" data-level="9.2.2" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#homogeneity-of-variance-tests"><i class="fa fa-check"></i><b>9.2.2</b> Homogeneity of Variance Tests</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#dealing-with-messy-data"><i class="fa fa-check"></i><b>9.3</b> Dealing with Messy Data</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#outliers"><i class="fa fa-check"></i><b>9.3.1</b> Outliers</a></li>
<li class="chapter" data-level="9.3.2" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#non-normal-data-and-unequal-variances"><i class="fa fa-check"></i><b>9.3.2</b> Non-normal Data and Unequal Variances</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#dealing-with-missing-data"><i class="fa fa-check"></i><b>9.4</b> Dealing with Missing Data</a></li>
<li class="chapter" data-level="9.5" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#summary"><i class="fa fa-check"></i><b>9.5</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html"><i class="fa fa-check"></i><b>10</b> Correlation and Simple Regression</a>
<ul>
<li class="chapter" data-level="10.1" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#correlation"><i class="fa fa-check"></i><b>10.1</b> Correlation</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#case-study-cucumber"><i class="fa fa-check"></i><b>10.1.1</b> Case Study: Cucumber</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#correlation-1"><i class="fa fa-check"></i><b>10.2</b> Correlation</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#how-is-r-calcuated-optional-reading"><i class="fa fa-check"></i><b>10.2.1</b> How Is r Calcuated (optional reading)</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#regression"><i class="fa fa-check"></i><b>10.3</b> Regression</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#case-study-5"><i class="fa fa-check"></i><b>10.3.1</b> Case Study</a></li>
<li class="chapter" data-level="10.3.2" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#linear-equation"><i class="fa fa-check"></i><b>10.3.2</b> Linear Equation</a></li>
<li class="chapter" data-level="10.3.3" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#calculating-the-regression-equation"><i class="fa fa-check"></i><b>10.3.3</b> Calculating the Regression Equation</a></li>
<li class="chapter" data-level="10.3.4" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#least-squares-estimate"><i class="fa fa-check"></i><b>10.3.4</b> Least-Squares Estimate</a></li>
<li class="chapter" data-level="10.3.5" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#significance-of-coefficients"><i class="fa fa-check"></i><b>10.3.5</b> Significance of Coefficients</a></li>
<li class="chapter" data-level="10.3.6" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#analysis-of-variance-4"><i class="fa fa-check"></i><b>10.3.6</b> Analysis of Variance</a></li>
<li class="chapter" data-level="10.3.7" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#measuring-model-fit-with-r-square"><i class="fa fa-check"></i><b>10.3.7</b> Measuring Model Fit with R-Square</a></li>
<li class="chapter" data-level="10.3.8" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#checking-whether-the-linear-model-is-appropriate"><i class="fa fa-check"></i><b>10.3.8</b> Checking whether the Linear Model is Appropriate</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#extrapolation"><i class="fa fa-check"></i><b>10.4</b> Extrapolation</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html"><i class="fa fa-check"></i><b>11</b> Nonlinear Relationships and Multiple Linear Regression</a>
<ul>
<li class="chapter" data-level="11.1" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#multiplie-linear-regression"><i class="fa fa-check"></i><b>11.1</b> Multiplie Linear Regression</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#case-study-modelling-yield-by-county"><i class="fa fa-check"></i><b>11.1.1</b> Case Study: Modelling Yield by County</a></li>
<li class="chapter" data-level="11.1.2" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#beware-of-bloated-models"><i class="fa fa-check"></i><b>11.1.2</b> Beware of Bloated Models</a></li>
<li class="chapter" data-level="11.1.3" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#methods-for-avoiding-bloated-models"><i class="fa fa-check"></i><b>11.1.3</b> Methods for Avoiding Bloated Models</a></li>
<li class="chapter" data-level="11.1.4" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#tunning-and-comparing-models"><i class="fa fa-check"></i><b>11.1.4</b> Tunning and Comparing Models</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#nonlinear-relationships"><i class="fa fa-check"></i><b>11.2</b> Nonlinear Relationships</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#fitting-nonlinear-responses-with-linear-regression"><i class="fa fa-check"></i><b>11.2.1</b> Fitting Nonlinear Responses with Linear Regression</a></li>
<li class="chapter" data-level="11.2.2" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#fitting-nonlinear-responses-with-nonlinear-regression"><i class="fa fa-check"></i><b>11.2.2</b> Fitting Nonlinear Responses with Nonlinear Regression</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#summary-1"><i class="fa fa-check"></i><b>11.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="spatial-statistics.html"><a href="spatial-statistics.html"><i class="fa fa-check"></i><b>12</b> Spatial Statistics</a>
<ul>
<li class="chapter" data-level="12.1" data-path="spatial-statistics.html"><a href="spatial-statistics.html#projection-general"><i class="fa fa-check"></i><b>12.1</b> Projection (General)</a>
<ul>
<li class="chapter" data-level="12.1.1" data-path="spatial-statistics.html"><a href="spatial-statistics.html#wgs-84-epsg-4236"><i class="fa fa-check"></i><b>12.1.1</b> WGS 84 (EPSG: 4236)</a></li>
<li class="chapter" data-level="12.1.2" data-path="spatial-statistics.html"><a href="spatial-statistics.html#mercator-epsg-3857"><i class="fa fa-check"></i><b>12.1.2</b> Mercator (EPSG: 3857)</a></li>
<li class="chapter" data-level="12.1.3" data-path="spatial-statistics.html"><a href="spatial-statistics.html#us-national-atlas-equal-area-epsg-2163"><i class="fa fa-check"></i><b>12.1.3</b> US National Atlas Equal Area (EPSG: 2163)</a></li>
<li class="chapter" data-level="12.1.4" data-path="spatial-statistics.html"><a href="spatial-statistics.html#utm-zone-11n-epsg-2955"><i class="fa fa-check"></i><b>12.1.4</b> UTM Zone 11N (EPSG: 2955)</a></li>
<li class="chapter" data-level="12.1.5" data-path="spatial-statistics.html"><a href="spatial-statistics.html#projection-summary"><i class="fa fa-check"></i><b>12.1.5</b> Projection Summary</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="spatial-statistics.html"><a href="spatial-statistics.html#shape-files"><i class="fa fa-check"></i><b>12.2</b> Shape Files</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="spatial-statistics.html"><a href="spatial-statistics.html#case-study-soybean-yield-in-iowa"><i class="fa fa-check"></i><b>12.2.1</b> Case Study: Soybean Yield in Iowa</a></li>
<li class="chapter" data-level="12.2.2" data-path="spatial-statistics.html"><a href="spatial-statistics.html#ssurgo"><i class="fa fa-check"></i><b>12.2.2</b> SSURGO</a></li>
<li class="chapter" data-level="12.2.3" data-path="spatial-statistics.html"><a href="spatial-statistics.html#operations-with-shapes"><i class="fa fa-check"></i><b>12.2.3</b> Operations with Shapes</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="spatial-statistics.html"><a href="spatial-statistics.html#rasters"><i class="fa fa-check"></i><b>12.3</b> Rasters</a>
<ul>
<li class="chapter" data-level="12.3.1" data-path="spatial-statistics.html"><a href="spatial-statistics.html#interpolation"><i class="fa fa-check"></i><b>12.3.1</b> Interpolation</a></li>
<li class="chapter" data-level="12.3.2" data-path="spatial-statistics.html"><a href="spatial-statistics.html#kriging"><i class="fa fa-check"></i><b>12.3.2</b> Kriging</a></li>
<li class="chapter" data-level="12.3.3" data-path="spatial-statistics.html"><a href="spatial-statistics.html#operations-on-kriged-data"><i class="fa fa-check"></i><b>12.3.3</b> Operations on Kriged Data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="machine-learning.html"><a href="machine-learning.html"><i class="fa fa-check"></i><b>13</b> Machine Learning</a>
<ul>
<li class="chapter" data-level="13.1" data-path="machine-learning.html"><a href="machine-learning.html#machine-learning-1"><i class="fa fa-check"></i><b>13.1</b> Machine Learning</a></li>
<li class="chapter" data-level="13.2" data-path="machine-learning.html"><a href="machine-learning.html#cluster-analyses"><i class="fa fa-check"></i><b>13.2</b> Cluster Analyses</a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="machine-learning.html"><a href="machine-learning.html#case-study-grouping-midwestern-environments"><i class="fa fa-check"></i><b>13.2.1</b> Case Study: Grouping Midwestern Environments</a></li>
<li class="chapter" data-level="13.2.2" data-path="machine-learning.html"><a href="machine-learning.html#scaling"><i class="fa fa-check"></i><b>13.2.2</b> Scaling</a></li>
<li class="chapter" data-level="13.2.3" data-path="machine-learning.html"><a href="machine-learning.html#clustering-animation"><i class="fa fa-check"></i><b>13.2.3</b> Clustering Animation</a></li>
<li class="chapter" data-level="13.2.4" data-path="machine-learning.html"><a href="machine-learning.html#county-cluster-analysis"><i class="fa fa-check"></i><b>13.2.4</b> County Cluster Analysis</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="machine-learning.html"><a href="machine-learning.html#k-nearest-neighbors"><i class="fa fa-check"></i><b>13.3</b> k-Nearest-Neighbors</a>
<ul>
<li class="chapter" data-level="13.3.1" data-path="machine-learning.html"><a href="machine-learning.html#case-study-guessing-county-yields-based-on-environmental-similarity"><i class="fa fa-check"></i><b>13.3.1</b> Case Study: Guessing County Yields based on Environmental Similarity</a></li>
<li class="chapter" data-level="13.3.2" data-path="machine-learning.html"><a href="machine-learning.html#scaling-1"><i class="fa fa-check"></i><b>13.3.2</b> Scaling</a></li>
<li class="chapter" data-level="13.3.3" data-path="machine-learning.html"><a href="machine-learning.html#k-nearest-neighbor-animation"><i class="fa fa-check"></i><b>13.3.3</b> k-Nearest-Neighbor Animation</a></li>
<li class="chapter" data-level="13.3.4" data-path="machine-learning.html"><a href="machine-learning.html#choosing-k"><i class="fa fa-check"></i><b>13.3.4</b> Choosing <span class="math inline">\(k\)</span></a></li>
<li class="chapter" data-level="13.3.5" data-path="machine-learning.html"><a href="machine-learning.html#model-cross-validation"><i class="fa fa-check"></i><b>13.3.5</b> Model Cross-Validation</a></li>
<li class="chapter" data-level="13.3.6" data-path="machine-learning.html"><a href="machine-learning.html#yield-prediction-with-nearest-neighbor-analysis"><i class="fa fa-check"></i><b>13.3.6</b> Yield Prediction with Nearest Neighbor Analysis</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="machine-learning.html"><a href="machine-learning.html#classification-trees"><i class="fa fa-check"></i><b>13.4</b> Classification Trees</a>
<ul>
<li class="chapter" data-level="13.4.1" data-path="machine-learning.html"><a href="machine-learning.html#features"><i class="fa fa-check"></i><b>13.4.1</b> Features</a></li>
<li class="chapter" data-level="13.4.2" data-path="machine-learning.html"><a href="machine-learning.html#quantitative-categorical-data"><i class="fa fa-check"></i><b>13.4.2</b> Quantitative (Categorical) Data</a></li>
<li class="chapter" data-level="13.4.3" data-path="machine-learning.html"><a href="machine-learning.html#quanatitiative-continuous-data"><i class="fa fa-check"></i><b>13.4.3</b> Quanatitiative (Continuous) Data</a></li>
<li class="chapter" data-level="13.4.4" data-path="machine-learning.html"><a href="machine-learning.html#overfitting-1"><i class="fa fa-check"></i><b>13.4.4</b> Overfitting</a></li>
<li class="chapter" data-level="13.4.5" data-path="machine-learning.html"><a href="machine-learning.html#cross-validation-1"><i class="fa fa-check"></i><b>13.4.5</b> Cross Validation</a></li>
<li class="chapter" data-level="13.4.6" data-path="machine-learning.html"><a href="machine-learning.html#random-forest"><i class="fa fa-check"></i><b>13.4.6</b> Random Forest</a></li>
<li class="chapter" data-level="13.4.7" data-path="machine-learning.html"><a href="machine-learning.html#feature-importance"><i class="fa fa-check"></i><b>13.4.7</b> Feature Importance</a></li>
</ul></li>
<li class="chapter" data-level="13.5" data-path="machine-learning.html"><a href="machine-learning.html#summary-2"><i class="fa fa-check"></i><b>13.5</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="putting-it-all-together.html"><a href="putting-it-all-together.html"><i class="fa fa-check"></i><b>14</b> Putting it all Together</a>
<ul>
<li class="chapter" data-level="14.1" data-path="putting-it-all-together.html"><a href="putting-it-all-together.html#scenario-1-yield-map-population-summary-and-z-distribution"><i class="fa fa-check"></i><b>14.1</b> Scenario 1: Yield Map (Population Summary and Z-Distribution)</a></li>
<li class="chapter" data-level="14.2" data-path="putting-it-all-together.html"><a href="putting-it-all-together.html#scenario-2-yield-estimate-sampling-t-distribution"><i class="fa fa-check"></i><b>14.2</b> Scenario 2: Yield Estimate (Sampling t-Distribution)</a></li>
<li class="chapter" data-level="14.3" data-path="putting-it-all-together.html"><a href="putting-it-all-together.html#scenario-3-side-by-side-t-test"><i class="fa fa-check"></i><b>14.3</b> Scenario 3: Side-By-Side (t-Test)</a></li>
<li class="chapter" data-level="14.4" data-path="putting-it-all-together.html"><a href="putting-it-all-together.html#scenario-4-fungicide-trial-anova-crd-or-rcbd"><i class="fa fa-check"></i><b>14.4</b> Scenario 4: Fungicide Trial (ANOVA CRD or RCBD)</a></li>
<li class="chapter" data-level="14.5" data-path="putting-it-all-together.html"><a href="putting-it-all-together.html#scenario-5-hybrid-response-to-fungicide-trial-anova-factorial-or-split-plot"><i class="fa fa-check"></i><b>14.5</b> Scenario 5: Hybrid Response to Fungicide Trial (ANOVA Factorial or Split Plot)</a></li>
<li class="chapter" data-level="14.6" data-path="putting-it-all-together.html"><a href="putting-it-all-together.html#scenario-6-foliar-rate-response-trial-linear-or-non-linear-regression"><i class="fa fa-check"></i><b>14.6</b> Scenario 6: Foliar Rate-Response Trial (Linear or Non-Linear Regression)</a></li>
<li class="chapter" data-level="14.7" data-path="putting-it-all-together.html"><a href="putting-it-all-together.html#scenario-7-application-map-shapefiles-and-rasters"><i class="fa fa-check"></i><b>14.7</b> Scenario 7: Application Map (Shapefiles and Rasters)</a></li>
<li class="chapter" data-level="14.8" data-path="putting-it-all-together.html"><a href="putting-it-all-together.html#scenario-8-yield-prediction-multiple-linear-regression-and-other-predictive-models"><i class="fa fa-check"></i><b>14.8</b> Scenario 8: Yield Prediction (Multiple Linear Regression and other Predictive Models)</a></li>
<li class="chapter" data-level="14.9" data-path="putting-it-all-together.html"><a href="putting-it-all-together.html#summary-3"><i class="fa fa-check"></i><b>14.9</b> Summary</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Data Science for Agricultural Professionals</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="nonlinear-relationships-and-multiple-linear-regression" class="section level1" number="11">
<h1><span class="header-section-number">Chapter 11</span> Nonlinear Relationships and Multiple Linear Regression</h1>
<p>In the last unit, we learned how to describe linear relationships between two variables, X and Y. <em>Correlation</em> was used when we wanted to measure the <em>association</em> between the two variables. This was appropriate when when, based on our “domain knowledge” (agronomy or our other specialty), we did not have insight into whether one variable affected the other, or whether a third, unknown variable affected the value of both. <em>Simple Linear Regression</em> was used when we had insight into the <em>causation</em> that linked two variables: we knew or hypothesized that a single response variable, <span class="math inline">\(Y\)</span>, was affected (and could be predicted) by a single predictor variable, <span class="math inline">\(X\)</span>.</p>
<p>Simple linear regression, however, has its limitations. First, simple linear regression is often too inadequate for modelling more complex systems. For example, a simple linear regression model might fit the effect of rainfall on corn yield. But we all realize that a prediction of corn yield based on rainfall alone will not be particularly accurate.</p>
<p>If we included additional predictor variables, such as a measure of heat (cumulative growing degree days) or soil texture (water holding capacity or clay content), we would likely predict yield more accurately. <em>Multiple Linear Regression</em> allows us to build model the relationship between a response variable, <span class="math inline">\(Y\)</span>, and multiple predictor variables, <span class="math inline">\(X_1\)</span>, <span class="math inline">\(X_2\)</span>, <span class="math inline">\(X_3\)</span>, etc.</p>
<p>Second, a linear model assumes the relationship between Y and X can be fit with a straight line. If you have taken a soil science course, however, you learned about <em>Leibig’s Law of the Minimum</em> and the <em>Mitscherlich Equation</em> that describe the relationship between nutrient availability and plant biomass. These relationships are curved and need to be fit with <em>Nonlinear Regression</em> models.</p>
<p>In this unit, we will learn how to use multiple linear regression to model yield responses to environment. We will also learn how to model nonlinear relationships, such as fertilizer response and plant growth</p>
<div id="multiplie-linear-regression" class="section level2" number="11.1">
<h2><span class="header-section-number">11.1</span> Multiplie Linear Regression</h2>
<p>In multiple linear regression, response variable Y is modeled as a function of multiple X variables:</p>
<p><span class="math display">\[ Y = \mu + X_1 + X_2 + X_3 ... X_n\]</span></p>
<div id="case-study-modelling-yield-by-county" class="section level3" number="11.1.1">
<h3><span class="header-section-number">11.1.1</span> Case Study: Modelling Yield by County</h3>
<p>We are going to work with a county-level dataset from Purdue university that includes soil characteristics, precipitation, corn, and soybean yield. I’ve become best-friends with this dataset during the past few years and have combined it with county-level weather data to build complex yield models. The authors used land use maps to exclude any acres not in crop production. Click the following link to access a little app with which to appreciate this dataset.</p>
<p>Here is the top of the data.frame:</p>
<div class="sourceCode" id="cb327"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb327-1"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb327-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb327-2"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb327-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb327-3"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb327-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(urbnmapr)</span>
<span id="cb327-4"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb327-4" aria-hidden="true" tabindex="-1"></a>counties <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">&quot;data-unit-11/county_environments.csv&quot;</span>)</span>
<span id="cb327-5"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb327-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb327-6"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb327-6" aria-hidden="true" tabindex="-1"></a><span class="do">## get county shapes ##</span></span>
<span id="cb327-7"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb327-7" aria-hidden="true" tabindex="-1"></a>counties_sf <span class="ot">=</span> <span class="fu">get_urbn_map</span>(<span class="st">&quot;counties&quot;</span>, <span class="at">sf =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb327-8"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb327-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rename</span>(<span class="at">stco =</span> county_fips) <span class="sc">%&gt;%</span></span>
<span id="cb327-9"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb327-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">stco =</span> <span class="fu">as.numeric</span>(stco))</span>
<span id="cb327-10"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb327-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb327-11"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb327-11" aria-hidden="true" tabindex="-1"></a>sf<span class="sc">::</span><span class="fu">st_crs</span>(counties_sf) <span class="ot">&lt;-</span> <span class="dv">9311</span></span></code></pre></div>
<pre><code>## old-style crs object detected; please recreate object with a recent sf::st_crs()</code></pre>
<div class="sourceCode" id="cb329"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb329-1"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb329-1" aria-hidden="true" tabindex="-1"></a>counties_w_env <span class="ot">=</span> counties_sf <span class="sc">%&gt;%</span></span>
<span id="cb329-2"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb329-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(counties) <span class="sc">%&gt;%</span></span>
<span id="cb329-3"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb329-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_as_sf</span>() <span class="sc">%&gt;%</span></span>
<span id="cb329-4"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb329-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="dv">4326</span>) <span class="sc">%&gt;%</span></span>
<span id="cb329-5"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb329-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gather</span>(feature, value, ppt<span class="sc">:</span>wheat)</span></code></pre></div>
<pre><code>## Joining, by = &quot;stco&quot;</code></pre>
<div class="sourceCode" id="cb331"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb331-1"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb331-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(counties)</span></code></pre></div>
<pre><code>##      county state  stco      ppt      whc     sand     silt      clay        om
## 1 Abbeville    SC 45001 562.2991 22.94693 39.26054 21.38839 39.351063  36.92471
## 2    Acadia    LA 22001 751.1478 37.83115 12.82896 54.19231 32.978734 105.79133
## 3  Accomack    VA 51001 584.6807 18.56290 74.82042 16.82072  8.358863 103.11425
## 4       Ada    ID 16001 124.9502 15.54825 44.49350 40.48000 15.026510  77.61499
## 5     Adair    IA 19001 598.4478 28.91851 17.82011 48.44056 33.739326 259.53255
## 6     Adair    KY 21001 698.6234 20.87349 15.66781 48.16733 36.164866  73.05356
##    kwfactor  kffactor      sph    slope  tfactor      corn  soybean  cotton
## 1 0.2045719 0.2044325 5.413008 42.59177 4.666834  57.75000 16.75385 525.500
## 2 0.4432803 0.4431914 6.370533 34.92266 4.855202  92.42500 28.72857      NA
## 3 0.2044544 0.2044544 5.166446       NA 4.011007 116.99714 30.44857 575.125
## 4 0.4106704 0.4198545 7.648190       NA 2.853957 145.74138       NA      NA
## 5 0.3541369 0.3541369 6.215139 55.24201 4.691089 133.02571 41.70857      NA
## 6 0.3166089 0.3725781 5.351832 37.65075 4.119289  95.76765 37.50000      NA
##      wheat
## 1 30.17500
## 2 38.11000
## 3 56.07407
## 4 97.26296
## 5 34.04000
## 6 37.42105</code></pre>
<p>How does corn yield respond to soil properties and precipitation in Minnesota and Wisconsin? Let’s say we want to model corn yield as a function of precipitation (ppt), percent sand (sand), percent clay (clay), percent organic matter (om) and soil pH (spH)? Our linear additive model would be:</p>
<p><span class="math display">\[ Y = \alpha + \beta _1 ppt + \beta _2 sand + \beta _3 clay + \beta _4 om + \beta _5 sph + \epsilon\]</span></p>
<p>First, we need to filter the dataset to MN and WI</p>
<div class="sourceCode" id="cb333"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb333-1"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb333-1" aria-hidden="true" tabindex="-1"></a>counties_mn_wi <span class="ot">=</span> counties <span class="sc">%&gt;%</span></span>
<span id="cb333-2"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb333-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(state <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">&quot;MN&quot;</span>, <span class="st">&quot;WI&quot;</span>))</span></code></pre></div>
<p>To fit our model, we use the linear model <em>lm()</em> function of R. For multiple regression, we don’t list any interactions between the terms.</p>
<div class="sourceCode" id="cb334"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb334-1"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb334-1" aria-hidden="true" tabindex="-1"></a>model_mn_wi <span class="ot">=</span> <span class="fu">lm</span>(corn <span class="sc">~</span> ppt <span class="sc">+</span> sand <span class="sc">+</span> clay <span class="sc">+</span> om <span class="sc">+</span> sph, <span class="at">data=</span>counties_mn_wi)</span>
<span id="cb334-2"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb334-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_mn_wi)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = corn ~ ppt + sand + clay + om + sph, data = counties_mn_wi)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -42.432  -4.342   1.108   7.035  23.278 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -189.02125   22.76727  -8.302 5.52e-14 ***
## ppt            0.37140    0.02165  17.159  &lt; 2e-16 ***
## sand          -0.33075    0.10746  -3.078  0.00248 ** 
## clay          -1.16506    0.24579  -4.740 4.92e-06 ***
## om            -0.01679    0.00307  -5.469 1.85e-07 ***
## sph           24.21303    2.02991  11.928  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 10.61 on 150 degrees of freedom
##   (3 observations deleted due to missingness)
## Multiple R-squared:  0.7651, Adjusted R-squared:  0.7573 
## F-statistic: 97.71 on 5 and 150 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Let’s go through the results. The first output item, the Call, is the linear model we gave to R.</p>
<p>The second item, residuals, describes the distribution of residuals around the regression model. We can see the minimum residual is 42 bu/acre below the predicted value. The maximum residual is 23 bu/acre above the predicted value. The middle 50% (between 1Q and 3Q) were between 4.3 below and 7.0 above the predicted values.</p>
<p>The Coefficients table is the highlight of our output. The table shows the estimated slopes <span class="math inline">\(\beta_1, \beta_2, \beta_3...\beta_n\)</span> associated with each environmental factor, plus the individual t-tests of their significance. We can see that each factor of our model is significant.</p>
<p>In the bottom, we see that three observations were deleted due to missingness (they didn’t have a value for each factor). Two <span class="math inline">\(R^2\)</span>s are presented. The multiple <span class="math inline">\(R^2\)</span> is the proportion of the total variance in the model explained by our regression model. This is the same concept as for simple linear regression. Our value is 0.77, which is pretty good for an environmental model like this, especially because we did not include any temperature data.</p>
</div>
<div id="beware-of-bloated-models" class="section level3" number="11.1.2">
<h3><span class="header-section-number">11.1.2</span> Beware of Bloated Models</h3>
<p>Multiple Linear Regression is a powerful tool, but it generally pays to be conservative in how many factors you include in a model. The more terms you include, the more you are likely to encounter problems with overfitting, multicollinearity, and heteroscedasticity.</p>
<div id="overfitting" class="section level4" number="11.1.2.1">
<h4><span class="header-section-number">11.1.2.1</span> Overfitting</h4>
<p>Every model contains fixed terms (which the model is meant to measure and predict) and random terms, such as error, which are beyond the scope of the model to predict. Not only that: since the error effect is random, it would be wrong for a model to try to predict it. If we add enough factors to a model, however, it will do exactly that. It will <em>overfit</em> the data. The problem with overfitting is that the model contorts itself to fit every nook and crany of one dataset – but fails to accurately predict values for additional datasets that, randomly, have different error structures.</p>
<p>Here is an analogy. You let your spouse or best friend borrow your car. When they return it, the seating settings are completely messed up. The lumbar support is either poking you in your but or about to break your neck. You either can’t reach the pedals and the steering wheel, or the seat is up so far you cannot even get in the car. In addition, the climate control is too hot or too cold. And, seeing what they left on the radio, you start to rethink the whole relationship.</p>
<p>This is exactly the problem with overfitting. The more we perfect the fit of a model one dataset, the more unlikely it is to make accurate predictions for another dataset.</p>
<p>Adding factors to a model will always increase the <span class="math inline">\(R^2\)</span> value, even if the new factor has nothing to do with what the model is predicting. For fun, lets create a column that randomly assigns an average number of Grateful Dead concerts attended per person, from 1 to 40, to each county.</p>
<div class="sourceCode" id="cb336"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb336-1"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb336-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">092220</span>)</span>
<span id="cb336-2"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb336-2" aria-hidden="true" tabindex="-1"></a>counties_mn_wi_gd <span class="ot">=</span> counties_mn_wi <span class="sc">%&gt;%</span></span>
<span id="cb336-3"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb336-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">gd_concerts =</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">40</span>), <span class="dv">159</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>))</span>
<span id="cb336-4"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb336-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(counties_mn_wi_gd)</span></code></pre></div>
<pre><code>##     county state  stco      ppt      whc     sand     silt      clay        om
## 1    Adams    WI 55001 548.2443 15.67212 78.38254 11.71815  9.899312  438.3402
## 2   Aitkin    MN 27001 485.5737 28.30823 47.94610 38.02355 14.030353 1760.8355
## 3    Anoka    MN 27003 551.9312 24.75840 75.16051 18.69882  6.140666 1787.7790
## 4  Ashland    WI 55003 495.9158 21.11778 43.10370 32.20112 24.695183  274.1879
## 5   Barron    WI 55005 528.5029 22.30522 58.10407 31.03742 10.858506  231.5082
## 6 Bayfield    WI 55007 490.7059 21.75064 34.08119 29.80771 36.111094  137.1594
##    kwfactor  kffactor      sph    slope  tfactor      corn  soybean cotton
## 1 0.1170651 0.1179408 6.068121 65.21191 4.521995 112.78000 34.08857     NA
## 2 0.3114794 0.3126979 6.405352 25.42843 3.700648  83.21111 27.98462     NA
## 3 0.1505643 0.1513100 6.248463 28.34023 4.432518 101.93429 27.70000     NA
## 4 0.2977456 0.3111864 6.638459 62.67817 4.265288  88.78421 24.00000     NA
## 5 0.2886149 0.2924627 5.710398 48.65562 3.943001 111.98000 33.79429     NA
## 6 0.2927169 0.2933493 7.166786 63.60773 4.636175  85.72857 22.40000     NA
##      wheat gd_concerts
## 1 40.32500          14
## 2 30.64000          38
## 3 35.05000          14
## 4 32.82857          25
## 5 44.49630          32
## 6 31.21429          35</code></pre>
<p>And then let’s check out our model:</p>
<div class="sourceCode" id="cb338"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb338-1"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb338-1" aria-hidden="true" tabindex="-1"></a>model_mn_wi_gd <span class="ot">=</span> <span class="fu">lm</span>(corn <span class="sc">~</span> ppt <span class="sc">+</span> sand <span class="sc">+</span> clay <span class="sc">+</span> om <span class="sc">+</span> sph <span class="sc">+</span> gd_concerts, <span class="at">data=</span>counties_mn_wi_gd)</span>
<span id="cb338-2"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb338-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_mn_wi_gd)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = corn ~ ppt + sand + clay + om + sph + gd_concerts, 
##     data = counties_mn_wi_gd)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -42.011  -4.216   1.347   6.880  23.572 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -1.887e+02  2.285e+01  -8.259 7.34e-14 ***
## ppt          3.716e-01  2.171e-02  17.116  &lt; 2e-16 ***
## sand        -3.313e-01  1.078e-01  -3.075  0.00251 ** 
## clay        -1.163e+00  2.465e-01  -4.720 5.39e-06 ***
## om          -1.681e-02  3.079e-03  -5.459 1.96e-07 ***
## sph          2.424e+01  2.036e+00  11.902  &lt; 2e-16 ***
## gd_concerts -2.998e-02  7.328e-02  -0.409  0.68305    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 10.64 on 149 degrees of freedom
##   (3 observations deleted due to missingness)
## Multiple R-squared:  0.7654, Adjusted R-squared:  0.7559 
## F-statistic:    81 on 6 and 149 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>See? Our Multiple <span class="math inline">\(R^2\)</span> increased slightly from 0.765 to 0.766. While this example is absurd, it points to a temptation for statisticians and data scientists: keep adding terms until the <span class="math inline">\(Multiple R^2\)</span> is an accepted value. Less nefariously, the researcher may just thinK the more variables the researcher can add, the better. We can now see this is wrong.</p>
</div>
<div id="multicollinearity" class="section level4" number="11.1.2.2">
<h4><span class="header-section-number">11.1.2.2</span> Multicollinearity</h4>
<p>Another problem that can occur as we add factors to our model is <em>multicollinearity</em>. Our linear model assumes that each factor has an <em>independent</em> effect on the response variable. We know, however, that is not always the case. For example, all sorts of weather and soil factors in our model can be related. Cloudy days associated with precipitation may decrease temperature. Warm temperatures may reduce soil moisture. Areas with greater precipitation will tend to have more woody vegetation, leading to lower soil pH and soil organic matter. Coarser soils, which are better drained, will tend to have lower soil organic matter.</p>
<p>Here is a hypothetical scenario: suppose we look at the regression of yield on precipitation and pH and conclude yield is significantly affected by both of them. Do we know that soil pH caused the change in yield? No, it’s possible that precipitation affected both pH and yield so that they appeared to change together. That’s not to say we can’t include all of these factors in our model. But we need to make certain that they are directly causing changes <em>to</em> the response variable, rather than responding <em>with</em> the response variable to a third variable in the model.</p>
</div>
<div id="heteroscedasticity" class="section level4" number="11.1.2.3">
<h4><span class="header-section-number">11.1.2.3</span> Heteroscedasticity</h4>
<p>The third problem we can have with a multiple linear regression model is that it is <em>heteroscedastic</em>. This indimidating term refers to unequal variances in our model. That is, the variance of observed yields varies markedly with the value being predicted. Multiple linear regression, like other linear models, assumes that the variance will be the same along all levels of the factors in the model. When heteroscedasticity – unequal variances – occurs, it jeopardizes our ability to fit the that factor. Our least squared estimate for that factor will be more influenced by factor levels with greater variances and less influences by levels with lesser variances.</p>
<p>One of the causes of heteroscedasticity is having many predictors – each with their own scales of measure and magnitudes – in a model. Since linear regression relies on least squares – that is, minimizing the differences between observed and predicted values – it will be more includenced by factors with greater variances than factors with small variances, regardless of how strongly each factor is correlated with yield.</p>
<p>The end result is that the regression model will fit the data more poorly. Its error will be greater and, thus, its F-value and p-value will be reduced. This may lead us to conclude a factor or the overall model does not explain a significant proportion of the variation in data, when in fact it does. In other words, we may commit at Type II error.</p>
</div>
</div>
<div id="methods-for-avoiding-bloated-models" class="section level3" number="11.1.3">
<h3><span class="header-section-number">11.1.3</span> Methods for Avoiding Bloated Models</h3>
<p>There are multiple approaches, and surely books written, about how to avoid overfitting and multicollinearity in models. After all that, also, model tuning (selecting the factors to include) seems to be art as much as science. This section provides an overview of methods used, which you might consider if presented with someone elses results, or if you are trying to construct a model with a few factors on your own.</p>
<div id="create-a-covariance-matrix" class="section level4" number="11.1.3.1">
<h4><span class="header-section-number">11.1.3.1</span> Create a Covariance Matrix</h4>
<p>A matrix (not “the matrix”) is a mathematical term that describes what you and I would call a table. So a covariance matrix is a table composed of correlation plots that we can use to inspect the covariance (or relationship) between each possible pair of variables in our dataset.</p>
<div class="sourceCode" id="cb340"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb340-1"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb340-1" aria-hidden="true" tabindex="-1"></a>yield_predictors <span class="ot">=</span> counties_mn_wi <span class="sc">%&gt;%</span></span>
<span id="cb340-2"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb340-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(corn, ppt, sand, clay, sph, om) <span class="sc">%&gt;%</span></span>
<span id="cb340-3"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb340-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na.omit</span>() <span class="sc">%&gt;%</span></span>
<span id="cb340-4"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb340-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span>
<span id="cb340-5"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb340-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb340-6"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb340-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(yield_predictors)</span></code></pre></div>
<p><img src="data-science-for-agricultural-professionals_files/figure-html/unnamed-chunk-216-1.png" width="672" /></p>
<p>To use the matrix, find the intersection between a column and a row containing two variables whose relationship you want to inspect. For example, in the fourth column, clay is plotted in relationship to the four other predictor variables, plus the response corn, in our model. In each plot, clay is on the X-axis, and the intersecting variable is on the Y-axis. Looking at the matrix, we notice the relationship of clay with sand and soil pH (sph) is visible. We may wonder, then, if the addition of clay to our model is improving our prediction.</p>
</div>
<div id="partial-correlation" class="section level4" number="11.1.3.2">
<h4><span class="header-section-number">11.1.3.2</span> Partial Correlation</h4>
<p>Another thing we can do to look for multicollinearity is to calculate the partial correlations. This can also be done with a simple line of code. Partial correlation shows the individual correlations between variables, with all other variables being held constant. What this does is allow us to quantify the correlation between two variables without worrying that both may be affected by a third variable. For example, we can look at the correlation between soil pH and soil organic matter without worrying that precipitation might be driving changes in both we could mistake for a relationship.</p>
<div class="sourceCode" id="cb341"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb341-1"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb341-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psych)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;psych&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:fBasics&#39;:
## 
##     tr</code></pre>
<pre><code>## The following object is masked from &#39;package:timeSeries&#39;:
## 
##     outlier</code></pre>
<pre><code>## The following object is masked from &#39;package:rcompanion&#39;:
## 
##     phi</code></pre>
<pre><code>## The following objects are masked from &#39;package:ggplot2&#39;:
## 
##     %+%, alpha</code></pre>
<div class="sourceCode" id="cb347"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb347-1"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb347-1" aria-hidden="true" tabindex="-1"></a><span class="fu">partial.r</span>(yield_predictors)</span></code></pre></div>
<pre><code>##            corn         ppt        sand       clay        sph         om
## corn  1.0000000  0.81392756 -0.24374133 -0.3609330  0.6977065 -0.4077095
## ppt   0.8139276  1.00000000 -0.03904489  0.2401821 -0.7798037  0.4618512
## sand -0.2437413 -0.03904489  1.00000000 -0.7743363  0.1767851  0.1169185
## clay -0.3609330  0.24018214 -0.77433626  1.0000000  0.5772645 -0.1893945
## sph   0.6977065 -0.77980370  0.17678512  0.5772645  1.0000000  0.4490715
## om   -0.4077095  0.46185116  0.11691848 -0.1893945  0.4490715  1.0000000</code></pre>
<p>The output of partial correlation is a matrix, which cross-tablulates the correlations among every predictor variables and reports their values in a table. The output abov tells us that sand and clay are both negatively correlated with corn. That’s odd – we would expect that as sand decreases, clay would increase, or vice versa – unless, both are being impacted by a third value, silt, which is not in our model.</p>
</div>
<div id="cross-validation" class="section level4" number="11.1.3.3">
<h4><span class="header-section-number">11.1.3.3</span> Cross Validation</h4>
<p>A third way to evaluate the performance of a model and to avoid mistaking over-prediction for true model performance is to use cross-validation. I’ll confess to graduating from Iowa State and making it another 15 years in academia and industry without having a clue about how important this is. If you plan to use your model not only to test hypotheses about variable significance, but to make predictions, the cross-validation is critical.</p>
<p>In cross-validation, the initial data are divided into <em>training</em> and <em>testing</em> groups. The model parameters (coefficients for slopes) are solved for using the training dataset. In general, all models will better fit the data used to train them. Therefore, the predictive performance of the model is measured using the testing dataset. In this way, the true performance of the model can be measured. In addition, the effect of adding or removing factors may be measured.</p>
<p>We will use a technique that sounds vaguely like an adult-alternative music group – Repeated 10-Fold Cross Validation. While the name sounds scary as all get-out, how it works is (pretty) straight forward:</p>
<ol style="list-style-type: decimal">
<li>Divide the data into 10 groups.</li>
<li>Randomly select 9 groups and fit the regression model to them. These groups are called the “training” dataset</li>
<li>Predict the responses for each observation in the tenth dataset, using the model fit to the other 9 datasets. This 10th dataset is called the “testing” dataset.</li>
<li>Use linear regression to determine the strength of the relationship between the predicted value and the actual values. Review summary statistics in comparing models.</li>
</ol>
<p>Here is the cross validation of our first yield model for Illinois and Ohio:</p>
<div class="sourceCode" id="cb349"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb349-1"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb349-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caret)</span></code></pre></div>
<pre><code>## Warning: package &#39;caret&#39; was built under R version 4.0.5</code></pre>
<pre><code>## Loading required package: lattice</code></pre>
<pre><code>## Warning: package &#39;lattice&#39; was built under R version 4.0.5</code></pre>
<pre><code>## 
## Attaching package: &#39;caret&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:survival&#39;:
## 
##     cluster</code></pre>
<pre><code>## The following object is masked from &#39;package:purrr&#39;:
## 
##     lift</code></pre>
<div class="sourceCode" id="cb356"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb356-1"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb356-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define training control</span></span>
<span id="cb356-2"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb356-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb356-3"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb356-3" aria-hidden="true" tabindex="-1"></a>train.control <span class="ot">&lt;-</span> <span class="fu">trainControl</span>(<span class="at">method =</span> <span class="st">&quot;repeatedcv&quot;</span>, </span>
<span id="cb356-4"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb356-4" aria-hidden="true" tabindex="-1"></a>                              <span class="at">number =</span> <span class="dv">10</span>, <span class="at">repeats =</span> <span class="dv">3</span>)</span>
<span id="cb356-5"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb356-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Train the model</span></span>
<span id="cb356-6"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb356-6" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">train</span>(corn <span class="sc">~</span> ppt <span class="sc">+</span> sand <span class="sc">+</span> clay <span class="sc">+</span> om <span class="sc">+</span> sph, <span class="at">data=</span>yield_predictors, <span class="at">method =</span> <span class="st">&quot;lm&quot;</span>,</span>
<span id="cb356-7"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb356-7" aria-hidden="true" tabindex="-1"></a>               <span class="at">trControl =</span> train.control)</span>
<span id="cb356-8"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb356-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Summarize the results</span></span>
<span id="cb356-9"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb356-9" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(model)</span></code></pre></div>
<pre><code>## Linear Regression 
## 
## 156 samples
##   5 predictor
## 
## No pre-processing
## Resampling: Cross-Validated (10 fold, repeated 3 times) 
## Summary of sample sizes: 140, 141, 140, 141, 140, 140, ... 
## Resampling results:
## 
##   RMSE      Rsquared   MAE     
##   10.82001  0.7630376  8.343696
## 
## Tuning parameter &#39;intercept&#39; was held constant at a value of TRUE</code></pre>
<p>We can see in the top of the output confirmation we are working with the original 5 predictors. To measure model performance, let’s look particularly at the MRSE and Rsquared statistics at the bottom. RMSE is the Root Mean Square Error, which you earlier learned is the square root of the Mean Square Error, and equivalent to the standard deviation of our data. This is expressed in our regression output above as residual standard error. An RMSE of 10.7 means the distribution of residuals (observed values) around our model predictions has a standard deviation of about 10.7. Thus 95% of our observed values would be expected to be within 21.4 bushels (2 * 10.7) of the predicted value.</p>
<p>The Rsquared statistic is the same as we have seen previously, and describes the amount of variation in the observed values explained by the predicted values.</p>
</div>
</div>
<div id="tunning-and-comparing-models" class="section level3" number="11.1.4">
<h3><span class="header-section-number">11.1.4</span> Tunning and Comparing Models</h3>
<p>Here is our original model for reference. Note that sand has a negative effect (-0.33075) on yield and that it is highly significant (p=0.00248).</p>
<div class="sourceCode" id="cb358"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb358-1"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb358-1" aria-hidden="true" tabindex="-1"></a>full_model <span class="ot">=</span> <span class="fu">lm</span>(corn <span class="sc">~</span> ppt <span class="sc">+</span> sand <span class="sc">+</span> clay <span class="sc">+</span> om <span class="sc">+</span> sph, <span class="at">data=</span>counties_mn_wi)</span>
<span id="cb358-2"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb358-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(full_model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = corn ~ ppt + sand + clay + om + sph, data = counties_mn_wi)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -42.432  -4.342   1.108   7.035  23.278 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -189.02125   22.76727  -8.302 5.52e-14 ***
## ppt            0.37140    0.02165  17.159  &lt; 2e-16 ***
## sand          -0.33075    0.10746  -3.078  0.00248 ** 
## clay          -1.16506    0.24579  -4.740 4.92e-06 ***
## om            -0.01679    0.00307  -5.469 1.85e-07 ***
## sph           24.21303    2.02991  11.928  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 10.61 on 150 degrees of freedom
##   (3 observations deleted due to missingness)
## Multiple R-squared:  0.7651, Adjusted R-squared:  0.7573 
## F-statistic: 97.71 on 5 and 150 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>We saw above that clay was strongly correlated with both sand and soil pH. Let’s drop clay from our model and see what happens:</p>
<div class="sourceCode" id="cb360"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb360-1"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb360-1" aria-hidden="true" tabindex="-1"></a>model_no_clay <span class="ot">=</span> <span class="fu">lm</span>(corn <span class="sc">~</span> ppt <span class="sc">+</span> sand <span class="sc">+</span> om <span class="sc">+</span> sph, <span class="at">data=</span>counties_mn_wi)</span>
<span id="cb360-2"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb360-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_no_clay)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = corn ~ ppt + sand + om + sph, data = counties_mn_wi)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -50.342  -5.438   1.410   7.135  22.276 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -2.031e+02  2.412e+01  -8.421 2.69e-14 ***
## ppt          3.815e-01  2.302e-02  16.575  &lt; 2e-16 ***
## sand         5.577e-02  7.479e-02   0.746    0.457    
## om          -1.607e-02  3.277e-03  -4.903 2.41e-06 ***
## sph          1.953e+01  1.895e+00  10.306  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 11.34 on 151 degrees of freedom
##   (3 observations deleted due to missingness)
## Multiple R-squared:  0.7299, Adjusted R-squared:  0.7227 
## F-statistic:   102 on 4 and 151 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>First, let’s look at the model fit. The Multiple R-squared decreased from 0.7651 to 0.7299. The residual standard error increased from 10.61 to 11.34. These would suggest the fit of the model has decreased, although we also notice the F-statistic has increased from 97.7 to 102, which suggests the model itself is more strongly detecting the combined effects of the factors on yield,</p>
<p>An additional statistic that we want to watch is the Adjusted R-Squared. This statistic not only takes into effect the percentage of the variation explained by the model, but how many factors were used to explain that variance. The model is penalized for according to the number of factors used: of two models that explained the same amount of variation, the one that used more factors would have a lower Adjusted R-square. We see the adjusted R-square decreased from our first model to the second.</p>
<p>Now let’s go back to sand. In the first model, it had a negative effect of -0.33075 and was highly significant. Now it has a positive effect of 5.577e-02 and an insignficant effect on corn yield. Remember, each factor in a linear regression model should be independent of the other factors. If we compare the other four factors, we will see their coefficients have changed slightly, but they have remained highly significant. This suggests that clay was affecting both sand content (after all, if you have more clay, you are likely to have less sand) and yield.</p>
<p>Let’s cross-validate the new model.</p>
<div class="sourceCode" id="cb362"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb362-1"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb362-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caret)</span>
<span id="cb362-2"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb362-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb362-3"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb362-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Define training control</span></span>
<span id="cb362-4"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb362-4" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb362-5"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb362-5" aria-hidden="true" tabindex="-1"></a>train.control <span class="ot">&lt;-</span> <span class="fu">trainControl</span>(<span class="at">method =</span> <span class="st">&quot;repeatedcv&quot;</span>, </span>
<span id="cb362-6"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb362-6" aria-hidden="true" tabindex="-1"></a>                              <span class="at">number =</span> <span class="dv">10</span>, <span class="at">repeats =</span> <span class="dv">3</span>)</span>
<span id="cb362-7"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb362-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Train the model</span></span>
<span id="cb362-8"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb362-8" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">train</span>(corn <span class="sc">~</span> ppt <span class="sc">+</span> sand <span class="sc">+</span> om <span class="sc">+</span> sph, <span class="at">data=</span>yield_predictors, <span class="at">method =</span> <span class="st">&quot;lm&quot;</span>,</span>
<span id="cb362-9"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb362-9" aria-hidden="true" tabindex="-1"></a>               <span class="at">trControl =</span> train.control)</span>
<span id="cb362-10"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb362-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Summarize the results</span></span>
<span id="cb362-11"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb362-11" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(model)</span></code></pre></div>
<pre><code>## Linear Regression 
## 
## 156 samples
##   4 predictor
## 
## No pre-processing
## Resampling: Cross-Validated (10 fold, repeated 3 times) 
## Summary of sample sizes: 140, 141, 140, 141, 140, 140, ... 
## Resampling results:
## 
##   RMSE      Rsquared   MAE     
##   11.08931  0.7415065  8.394927
## 
## Tuning parameter &#39;intercept&#39; was held constant at a value of TRUE</code></pre>
<p>We see the Rsquared and RMSE (root mean square error) are statistics are slightly lower than the original model in the cross-validation, too.</p>
<p>Since sand was insignificant in the second model, let’s remove it and rerun our model.</p>
<div class="sourceCode" id="cb364"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb364-1"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb364-1" aria-hidden="true" tabindex="-1"></a>model_no_clay_sand <span class="ot">=</span> <span class="fu">lm</span>(corn <span class="sc">~</span> ppt <span class="sc">+</span> om <span class="sc">+</span> sph, <span class="at">data=</span>counties_mn_wi)</span>
<span id="cb364-2"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb364-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_no_clay_sand)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = corn ~ ppt + om + sph, data = counties_mn_wi)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -50.786  -5.803   1.263   6.637  22.088 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -1.904e+02  1.702e+01 -11.187  &lt; 2e-16 ***
## ppt          3.724e-01  1.943e-02  19.167  &lt; 2e-16 ***
## om          -1.501e-02  2.949e-03  -5.089 1.05e-06 ***
## sph          1.863e+01  1.465e+00  12.720  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 11.32 on 152 degrees of freedom
##   (3 observations deleted due to missingness)
## Multiple R-squared:  0.7289, Adjusted R-squared:  0.7236 
## F-statistic: 136.2 on 3 and 152 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>We see little change in the Multiple R-squared or Adjusted R-squared, but the F-statistic has again increased. Let’s cross-validate the model.</p>
<div class="sourceCode" id="cb366"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb366-1"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb366-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caret)</span>
<span id="cb366-2"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb366-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb366-3"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb366-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Define training control</span></span>
<span id="cb366-4"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb366-4" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb366-5"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb366-5" aria-hidden="true" tabindex="-1"></a>train.control <span class="ot">&lt;-</span> <span class="fu">trainControl</span>(<span class="at">method =</span> <span class="st">&quot;repeatedcv&quot;</span>, </span>
<span id="cb366-6"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb366-6" aria-hidden="true" tabindex="-1"></a>                              <span class="at">number =</span> <span class="dv">10</span>, <span class="at">repeats =</span> <span class="dv">3</span>)</span>
<span id="cb366-7"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb366-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Train the model</span></span>
<span id="cb366-8"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb366-8" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">train</span>(corn <span class="sc">~</span> ppt <span class="sc">+</span> om <span class="sc">+</span> sph, <span class="at">data=</span>yield_predictors, <span class="at">method =</span> <span class="st">&quot;lm&quot;</span>,</span>
<span id="cb366-9"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb366-9" aria-hidden="true" tabindex="-1"></a>               <span class="at">trControl =</span> train.control)</span>
<span id="cb366-10"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb366-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Summarize the results</span></span>
<span id="cb366-11"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb366-11" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(model)</span></code></pre></div>
<pre><code>## Linear Regression 
## 
## 156 samples
##   3 predictor
## 
## No pre-processing
## Resampling: Cross-Validated (10 fold, repeated 3 times) 
## Summary of sample sizes: 140, 141, 140, 141, 140, 140, ... 
## Resampling results:
## 
##   RMSE      Rsquared   MAE     
##   11.05355  0.7437791  8.331748
## 
## Tuning parameter &#39;intercept&#39; was held constant at a value of TRUE</code></pre>
<p>We see the new model fits slightly better.</p>
<p>We could go on and on with the process. We might try adding silt into the model to replace the sand and clay we removed. Water holding capacity was a factor in the original dataset – we might try using that as a proxy, too. But the interations we have gone through show us that bigger models are not necessarily better (not by much, in any case). While we can build complex models with multiple linear regression, it is better not to when possible.</p>
</div>
</div>
<div id="nonlinear-relationships" class="section level2" number="11.2">
<h2><span class="header-section-number">11.2</span> Nonlinear Relationships</h2>
<p>As mentioned in the introduction, there are many relationships between variables that are nonlinear – that is, cannot be modelled with a straight line. In reality, few relationships in agronomy are perfectly linear, so by nonlinear we mean relationships where a linear model would systematically over-predict or underpredict the response variable. In the plot below, a disease population (infected plants per plot) is modeled as a function of days since infection.<br />
As with many pest populations, the number of infections increases exponentially with time. We can see how a linear model would underpredict the number of plants from 7 to 9 days after infection and again from 25 to 27 days after infection, while overpredicting the number of infected plants from 15 to 21 days after infection . Systematic overpredictions or underpredictions are called <em>bias</em>.</p>
<div class="sourceCode" id="cb368"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb368-1"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb368-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb368-2"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb368-2" aria-hidden="true" tabindex="-1"></a>exponential <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">x =</span> <span class="fu">seq</span>(<span class="at">from=</span><span class="dv">7</span>, <span class="at">to=</span><span class="dv">28</span>, <span class="at">by=</span><span class="dv">2</span>))</span>
<span id="cb368-3"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb368-3" aria-hidden="true" tabindex="-1"></a>exponential_final <span class="ot">=</span> exponential <span class="sc">%&gt;%</span></span>
<span id="cb368-4"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb368-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">y =</span> <span class="fu">exp</span>(x<span class="sc">/</span><span class="dv">7</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb368-5"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb368-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">log_y =</span> <span class="fu">log</span>(y)) </span>
<span id="cb368-6"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb368-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb368-7"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb368-7" aria-hidden="true" tabindex="-1"></a>exponential_final <span class="sc">%&gt;%</span></span>
<span id="cb368-8"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb368-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>x, <span class="at">y=</span>y)) <span class="sc">+</span></span>
<span id="cb368-9"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb368-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size=</span><span class="dv">2</span>, <span class="at">color=</span><span class="st">&quot;blue&quot;</span>) <span class="sc">+</span></span>
<span id="cb368-10"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb368-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">&#39;lm&#39;</span>, <span class="at">color =</span> <span class="st">&quot;tomato&quot;</span>, <span class="at">se=</span><span class="cn">FALSE</span>) <span class="sc">+</span> </span>
<span id="cb368-11"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb368-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Days after Infection&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Infected Plants per Plot&quot;</span>) <span class="sc">+</span></span>
<span id="cb368-12"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb368-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lims</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="dv">7</span>,<span class="dv">28</span>), <span class="at">y=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">50</span>)) <span class="sc">+</span></span>
<span id="cb368-13"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb368-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">18</span>),</span>
<span id="cb368-14"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb368-14" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">14</span>))</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<pre><code>## Warning: Removed 8 rows containing missing values (geom_smooth).</code></pre>
<p><img src="data-science-for-agricultural-professionals_files/figure-html/unnamed-chunk-224-1.png" width="672" /></p>
<p>Instead, we can fit the data with an exponential model that reduces the bias and increases the precision of our model:</p>
<div class="sourceCode" id="cb371"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb371-1"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb371-1" aria-hidden="true" tabindex="-1"></a>exponential_final <span class="sc">%&gt;%</span></span>
<span id="cb371-2"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb371-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>x, <span class="at">y=</span>y)) <span class="sc">+</span></span>
<span id="cb371-3"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb371-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size=</span><span class="dv">2</span>, <span class="at">color=</span><span class="st">&quot;blue&quot;</span>) <span class="sc">+</span></span>
<span id="cb371-4"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb371-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">&#39;loess&#39;</span>, <span class="at">color =</span> <span class="st">&quot;tomato&quot;</span>, <span class="at">se=</span><span class="cn">FALSE</span>) <span class="sc">+</span> </span>
<span id="cb371-5"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb371-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Days after Infection&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Infected Plants per Plot&quot;</span>) <span class="sc">+</span></span>
<span id="cb371-6"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb371-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lims</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="dv">7</span>,<span class="dv">28</span>), <span class="at">y=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">50</span>)) <span class="sc">+</span></span>
<span id="cb371-7"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb371-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">18</span>),</span>
<span id="cb371-8"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb371-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">14</span>))</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="data-science-for-agricultural-professionals_files/figure-html/unnamed-chunk-225-1.png" width="672" /></p>
<div id="fitting-nonlinear-responses-with-linear-regression" class="section level3" number="11.2.1">
<h3><span class="header-section-number">11.2.1</span> Fitting Nonlinear Responses with Linear Regression</h3>
<p>Fitting a relationship with a simple linear regression model is simpler than fitting it with a nonlinear model, which we will soon see. Exponential relationships, like the one above can be fit by <em>transforming</em> the data to a new scale. This is the same concept as we used in an earlier unit to work with messy data.</p>
<div id="exponential-model" class="section level4" number="11.2.1.1">
<h4><span class="header-section-number">11.2.1.1</span> Exponential Model</h4>
<p>For example, the data above (and many exponential relationships in biology and other disciplines can be transformed using the natural log:</p>
<p><span class="math display">\[ y = log(x)\]</span></p>
<p>If our original dataset looks like:</p>
<div class="sourceCode" id="cb373"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb373-1"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb373-1" aria-hidden="true" tabindex="-1"></a>exponential_final <span class="sc">%&gt;%</span></span>
<span id="cb373-2"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb373-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(x, y)</span></code></pre></div>
<pre><code>##     x         y
## 1   7  2.718282
## 2   9  3.617251
## 3  11  4.813520
## 4  13  6.405409
## 5  15  8.523756
## 6  17 11.342667
## 7  19 15.093825
## 8  21 20.085537
## 9  23 26.728069
## 10 25 35.567367
## 11 27 47.329930</code></pre>
<p>Where x is the days since infection and y is the mean number of infections per plot.
We can create a new column, log_y with the natural log of infected plants.</p>
<div class="sourceCode" id="cb375"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb375-1"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb375-1" aria-hidden="true" tabindex="-1"></a>exponential_final <span class="sc">%&gt;%</span></span>
<span id="cb375-2"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb375-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(x, y) <span class="sc">%&gt;%</span></span>
<span id="cb375-3"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb375-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">log_y =</span> <span class="fu">log</span>(y))</span></code></pre></div>
<pre><code>##     x         y    log_y
## 1   7  2.718282 1.000000
## 2   9  3.617251 1.285714
## 3  11  4.813520 1.571429
## 4  13  6.405409 1.857143
## 5  15  8.523756 2.142857
## 6  17 11.342667 2.428571
## 7  19 15.093825 2.714286
## 8  21 20.085537 3.000000
## 9  23 26.728069 3.285714
## 10 25 35.567367 3.571429
## 11 27 47.329930 3.857143</code></pre>
<p>When we fit the log of the infected plants, we see the relationship between the number of infected plants and days since infection is now linear.</p>
<div class="sourceCode" id="cb377"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb377-1"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb377-1" aria-hidden="true" tabindex="-1"></a>exponential_final <span class="sc">%&gt;%</span></span>
<span id="cb377-2"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb377-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>x, <span class="at">y=</span>log_y)) <span class="sc">+</span></span>
<span id="cb377-3"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb377-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size=</span><span class="dv">2</span>, <span class="at">color=</span><span class="st">&quot;blue&quot;</span>) <span class="sc">+</span></span>
<span id="cb377-4"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb377-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">&#39;loess&#39;</span>, <span class="at">color =</span> <span class="st">&quot;tomato&quot;</span>, <span class="at">se=</span><span class="cn">FALSE</span>) <span class="sc">+</span> </span>
<span id="cb377-5"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb377-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Days after Infection&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Infected Plants per Plot&quot;</span>) <span class="sc">+</span></span>
<span id="cb377-6"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb377-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lims</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="dv">7</span>,<span class="dv">28</span>), <span class="at">y=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">5</span>)) <span class="sc">+</span></span>
<span id="cb377-7"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb377-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">18</span>),</span>
<span id="cb377-8"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb377-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">14</span>))</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="data-science-for-agricultural-professionals_files/figure-html/unnamed-chunk-228-1.png" width="672" /></p>
<p>We can now fit a linear model to the relationship between infected plants and days after infection.</p>
<div class="sourceCode" id="cb379"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb379-1"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb379-1" aria-hidden="true" tabindex="-1"></a>names</span></code></pre></div>
<pre><code>## function (x)  .Primitive(&quot;names&quot;)</code></pre>
<div class="sourceCode" id="cb381"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb381-1"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb381-1" aria-hidden="true" tabindex="-1"></a>infection_linear_model <span class="ot">=</span> <span class="fu">lm</span>(log_y <span class="sc">~</span> x, exponential_final)</span>
<span id="cb381-2"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb381-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(infection_linear_model)</span></code></pre></div>
<pre><code>## Warning in summary.lm(infection_linear_model): essentially perfect fit: summary
## may be unreliable</code></pre>
<pre><code>## 
## Call:
## lm(formula = log_y ~ x, data = exponential_final)
## 
## Residuals:
##        Min         1Q     Median         3Q        Max 
## -4.375e-16 -3.117e-16 -3.760e-18  2.469e-16  5.395e-16 
## 
## Coefficients:
##              Estimate Std. Error   t value Pr(&gt;|t|)    
## (Intercept) 2.142e-15  3.108e-16 6.893e+00 7.12e-05 ***
## x           1.429e-01  1.713e-17 8.337e+15  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.594e-16 on 9 degrees of freedom
## Multiple R-squared:      1,  Adjusted R-squared:      1 
## F-statistic: 6.951e+31 on 1 and 9 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Our linear model, from the equation above, is:</p>
<p><span class="math display">\[ log_y = 0 + 0.1429 \times x\]</span></p>
<p>Just to test the model, let’s predict the number of infected plants when x = 15</p>
<div class="sourceCode" id="cb384"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb384-1"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb384-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">&quot;log_y =&quot;</span>, <span class="dv">0</span> <span class="sc">+</span> <span class="fl">0.1429</span><span class="sc">*</span><span class="dv">15</span>)</span></code></pre></div>
<pre><code>## [1] &quot;log_y = 2.1435&quot;</code></pre>
<p>We can see this value is approximately the number of infected plants 15 days after infection in the table above. Any predicted value can be transformed from the logaritm back to the original scale using the <em>exp()</em> function. Compare this with the original count, y, in the table above.</p>
<div class="sourceCode" id="cb386"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb386-1"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb386-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">&quot;y =&quot;</span>, <span class="fu">exp</span>(<span class="fl">2.1435</span>))</span></code></pre></div>
<pre><code>## [1] &quot;y = 8.52923778043145&quot;</code></pre>
</div>
<div id="parabolic" class="section level4" number="11.2.1.2">
<h4><span class="header-section-number">11.2.1.2</span> Parabolic</h4>
<p>In nutrient availability and plant density models, we sometimes encounter data that are parabolic – the relationship between Y and X resembles a <span class="math inline">\(\bigcap\)</span> or <span class="math inline">\(\bigcup\)</span> shape. These data can be fit with a <em>quadratic model</em>. Remember that beast from eighth grade algebra. Don’t worry – we don’t have decompose it!</p>
<p>Let’s say we have data from a plant density study in corn:</p>
<div class="sourceCode" id="cb388"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb388-1"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb388-1" aria-hidden="true" tabindex="-1"></a>plant_density_data_pre <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">pop =</span> <span class="fu">seq</span>(<span class="dv">28</span>, <span class="dv">44</span>, <span class="dv">4</span>),</span>
<span id="cb388-2"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb388-2" aria-hidden="true" tabindex="-1"></a>                                <span class="at">yield =</span> <span class="fu">c</span>(<span class="dv">170</span>, <span class="dv">200</span>, <span class="dv">205</span>, <span class="dv">200</span>,<span class="dv">170</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb388-3"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb388-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pop2 =</span> pop<span class="sc">^</span><span class="dv">2</span>) </span>
<span id="cb388-4"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb388-4" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb388-5"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb388-5" aria-hidden="true" tabindex="-1"></a>pop_model <span class="ot">=</span> <span class="fu">lm</span>(yield <span class="sc">~</span> pop <span class="sc">+</span> pop2, <span class="at">data =</span> plant_density_data_pre)</span>
<span id="cb388-6"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb388-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb388-7"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb388-7" aria-hidden="true" tabindex="-1"></a>plant_density_data <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">pop =</span> <span class="fu">seq</span>(<span class="dv">28</span>, <span class="dv">44</span>, <span class="dv">2</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb388-8"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb388-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pop2 =</span> pop<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb388-9"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb388-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb388-10"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb388-10" aria-hidden="true" tabindex="-1"></a>plant_density_data<span class="sc">$</span>yield <span class="ot">=</span> <span class="fu">predict</span>(pop_model, plant_density_data)</span>
<span id="cb388-11"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb388-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb388-12"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb388-12" aria-hidden="true" tabindex="-1"></a>plant_density_data <span class="sc">%&gt;%</span></span>
<span id="cb388-13"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb388-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> pop, <span class="at">y =</span> yield)) <span class="sc">+</span></span>
<span id="cb388-14"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb388-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code></pre></div>
<p><img src="data-science-for-agricultural-professionals_files/figure-html/unnamed-chunk-232-1.png" width="672" /></p>
<p>The quadratic model is:</p>
<p><span class="math display">\[ Y = \alpha + \beta X + \gamma X^2\]</span>
Where <span class="math inline">\(\alpha\)</span> is the Y-intercept, and <span class="math inline">\(\beta\)</span> and <span class="math inline">\(\gamma\)</span> are the coefficients associated with <span class="math inline">\(X\)</span> and <span class="math inline">\(X^2\)</span>. We can run this model the same as we would a simple regression.</p>
<div class="sourceCode" id="cb389"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb389-1"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb389-1" aria-hidden="true" tabindex="-1"></a>pop_model <span class="ot">=</span> <span class="fu">lm</span>(yield <span class="sc">~</span> pop <span class="sc">+</span> pop2, <span class="at">data =</span> plant_density_data)</span>
<span id="cb389-2"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb389-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(pop_model)</span></code></pre></div>
<pre><code>## Warning in summary.lm(pop_model): essentially perfect fit: summary may be
## unreliable</code></pre>
<pre><code>## 
## Call:
## lm(formula = yield ~ pop + pop2, data = plant_density_data)
## 
## Residuals:
##        Min         1Q     Median         3Q        Max 
## -8.565e-14 -3.115e-14 -7.869e-15  4.033e-14  7.242e-14 
## 
## Coefficients:
##               Estimate Std. Error    t value Pr(&gt;|t|)    
## (Intercept) -5.446e+02  1.043e-12 -5.223e+14   &lt;2e-16 ***
## pop          4.179e+01  5.877e-14  7.111e+14   &lt;2e-16 ***
## pop2        -5.804e-01  8.146e-16 -7.125e+14   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 5.718e-14 on 6 degrees of freedom
## Multiple R-squared:      1,  Adjusted R-squared:      1 
## F-statistic: 2.538e+29 on 2 and 6 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>This output should look very similar to the simple linear regression output. The only difference is that there are now three coefficients returned: the intercept (<span class="math inline">\(\alpha\)</span> above), the coefficient for pop (<span class="math inline">\(\beta\)</span> above), and the coefficent for pop2 (<span class="math inline">\(\gamma\)</span> above).</p>
</div>
</div>
<div id="fitting-nonlinear-responses-with-nonlinear-regression" class="section level3" number="11.2.2">
<h3><span class="header-section-number">11.2.2</span> Fitting Nonlinear Responses with Nonlinear Regression</h3>
<p>Other nonlinear relationships must be fit with nonlinear regression. Nonlinear regression differs from linear regression in a couple of ways. First, a nonlinear regression model may include multiple coefficients, but only X as a predictor variable. Second, models are not fit to nonlinear data using the same approach (using least square means to solve for slope) as with linear data. Models are often to nonlinear data often do so using a “trial and error” approach, comparing multiple models before converging on the model that fits best. To help this process along, data scientists must often “guestimate” the initial values of model parameters and include that in the code.</p>
<div id="monomolecular" class="section level4" number="11.2.2.1">
<h4><span class="header-section-number">11.2.2.1</span> Monomolecular</h4>
<p>In the Monomolecular growth model, the response variable Y initially increases rapidly with increases in X. Then the rate of increase slows, until Y plateaus and does not increase further with X. In the example below, the response of corn yield to nitrogen fertilization rate is modelled with the monomolecular (asymptotic) function.</p>
<p>First, we load and plot the data.</p>
<div class="sourceCode" id="cb392"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb392-1"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb392-1" aria-hidden="true" tabindex="-1"></a>corn_n_mono <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">&quot;data-unit-11/corn_nrate_mono.csv&quot;</span>)</span>
<span id="cb392-2"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb392-2" aria-hidden="true" tabindex="-1"></a>p <span class="ot">=</span> corn_n_mono <span class="sc">%&gt;%</span></span>
<span id="cb392-3"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb392-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>n_rate, <span class="at">y=</span>yield)) <span class="sc">+</span></span>
<span id="cb392-4"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb392-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color=</span><span class="st">&quot;blue&quot;</span>)</span></code></pre></div>
<p>Then we fit our nonlinear model.</p>
<div class="sourceCode" id="cb393"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb393-1"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb393-1" aria-hidden="true" tabindex="-1"></a>corn_n_mono_asym <span class="ot">=</span> stats<span class="sc">::</span><span class="fu">nls</span>(yield <span class="sc">~</span> <span class="fu">SSasymp</span>(n_rate,init,m,plateau), <span class="at">data=</span>corn_n_mono)</span>
<span id="cb393-2"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb393-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(corn_n_mono_asym)</span></code></pre></div>
<pre><code>## 
## Formula: yield ~ SSasymp(n_rate, init, m, plateau)
## 
## Parameters:
##         Estimate Std. Error t value Pr(&gt;|t|)    
## init    160.6633     5.7363   28.01 5.24e-13 ***
## m        96.6297     4.3741   22.09 1.08e-11 ***
## plateau  -4.2634     0.3019  -14.12 2.90e-09 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 8.76 on 13 degrees of freedom
## 
## Number of iterations to convergence: 0 
## Achieved convergence tolerance: 6.133e-08</code></pre>
<p>The most important part of this output is the bottom line, “Achieved convergence tolerance”. That means our model successfully fit the data.</p>
<p>Finally, we can add our modelled curve to our initial plot:</p>
<div class="sourceCode" id="cb395"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb395-1"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb395-1" aria-hidden="true" tabindex="-1"></a>test_data <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">n_rate =</span> <span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">240</span>,<span class="dv">1</span>))</span>
<span id="cb395-2"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb395-2" aria-hidden="true" tabindex="-1"></a>test_data<span class="sc">$</span>pred <span class="ot">=</span> <span class="fu">predict</span>(corn_n_mono_asym, test_data)</span>
<span id="cb395-3"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb395-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb395-4"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb395-4" aria-hidden="true" tabindex="-1"></a>p <span class="sc">+</span> <span class="fu">geom_line</span>(<span class="at">data =</span> test_data, <span class="fu">aes</span>(<span class="at">x=</span>n_rate, <span class="at">y=</span>pred), <span class="at">color=</span><span class="st">&quot;tomato&quot;</span>)</span></code></pre></div>
<p><img src="data-science-for-agricultural-professionals_files/figure-html/unnamed-chunk-236-1.png" width="672" /></p>
<p>In the plot above, the points represent observed values, while the red line represents the values predicted by the monomolecular model. The monomolecular function is often used to represent fertilizer rate or soil nutrient content, since the response to many fertilizers plateaus or “maxes out”. Fertilizer rate recommendations are developed to increase fertilization up to the point where the cost of adding another unit of fertilizer exceeds the benefit of the increase in yield. The monomolecular function can also measure other “diminishing returns” responses, such as the response of photosynthesis to increasing leaf area.</p>
</div>
<div id="logistic-model" class="section level4" number="11.2.2.2">
<h4><span class="header-section-number">11.2.2.2</span> Logistic Model</h4>
<p>The <em>Logistic</em> and model is often used in “growth analysis”, studies that highlight patterns of plant growth, particularly cumulative biomass accumulation over time. Data generally follow a “sigmoidal”, or S-shaped, pattern. In early growth the rate of biomass accumulation slowly increases. In the intermediate growth phase, biomass accumulation is rapid and linear. In the final growth phase, the rate of growth decreases and, if the trial is long enough, may plateau.</p>
<p>In the plot below, total dry matter accumulation (tdm) is shown in relation to days after emergence (dae).</p>
<div class="sourceCode" id="cb396"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb396-1"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb396-1" aria-hidden="true" tabindex="-1"></a>soybean_tdm <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">&quot;data-unit-11/soybean_dae_tdm_logis.csv&quot;</span>)</span>
<span id="cb396-2"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb396-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb396-3"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb396-3" aria-hidden="true" tabindex="-1"></a>p_soy <span class="ot">=</span> soybean_tdm <span class="sc">%&gt;%</span></span>
<span id="cb396-4"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb396-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>dae, <span class="at">y=</span>tdm)) <span class="sc">+</span></span>
<span id="cb396-5"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb396-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color=</span><span class="st">&quot;blue&quot;</span>)</span>
<span id="cb396-6"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb396-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb396-7"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb396-7" aria-hidden="true" tabindex="-1"></a>p_soy</span></code></pre></div>
<p><img src="data-science-for-agricultural-professionals_files/figure-html/unnamed-chunk-237-1.png" width="672" /></p>
<p>The “S” shape of the data is very pronounced. Next, we fit a logistic growth curve to the data:</p>
<div class="sourceCode" id="cb397"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb397-1"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb397-1" aria-hidden="true" tabindex="-1"></a>soybean_tdm_model <span class="ot">=</span> stats<span class="sc">::</span><span class="fu">nls</span>(tdm <span class="sc">~</span> <span class="fu">SSlogis</span>(dae, Asym, xmid, scal), <span class="at">data=</span>soybean_tdm)</span>
<span id="cb397-2"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb397-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(soybean_tdm_model)</span></code></pre></div>
<pre><code>## 
## Formula: tdm ~ SSlogis(dae, Asym, xmid, scal)
## 
## Parameters:
##      Estimate Std. Error t value Pr(&gt;|t|)    
## Asym 857.5043    11.7558   72.94 2.12e-07 ***
## xmid  59.7606     0.7525   79.42 1.51e-07 ***
## scal  10.8261     0.6574   16.47 7.96e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 14.64 on 4 degrees of freedom
## 
## Number of iterations to convergence: 0 
## Achieved convergence tolerance: 3.029e-06</code></pre>
<p>We see again in the output that the model achieved convergence tolerance. Another thing to note is the “Number of iterations to convergence”. It took this model 9 steps to fit the data. The algorithm will typically quit after 50 unsuccessful attempts. When that occurs, it may be an indication the data should be fit with a different model.</p>
<p>Here is our data with the fitted prediction model:</p>
<div class="sourceCode" id="cb399"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb399-1"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb399-1" aria-hidden="true" tabindex="-1"></a>test_data_soy <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">dae=</span><span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">120</span>,<span class="dv">1</span>))</span>
<span id="cb399-2"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb399-2" aria-hidden="true" tabindex="-1"></a>test_data_soy<span class="sc">$</span>pred <span class="ot">=</span> <span class="fu">predict</span>(soybean_tdm_model, test_data_soy)</span>
<span id="cb399-3"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb399-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb399-4"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb399-4" aria-hidden="true" tabindex="-1"></a>p_soy <span class="sc">+</span> <span class="fu">geom_line</span>(<span class="at">data =</span> test_data_soy, <span class="fu">aes</span>(<span class="at">x=</span>dae, <span class="at">y=</span>pred), <span class="at">color=</span><span class="st">&quot;tomato&quot;</span>)</span></code></pre></div>
<p><img src="data-science-for-agricultural-professionals_files/figure-html/unnamed-chunk-239-1.png" width="672" /></p>
<p>We can see this again illustrated in the next plot, which illustrates the effect of wetting period on the intensity of wheat blast.</p>
<div class="sourceCode" id="cb400"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb400-1"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb400-1" aria-hidden="true" tabindex="-1"></a>wheat_blast <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">&quot;data-unit-11/wheat_blast_wetting_intensity.csv&quot;</span>)</span>
<span id="cb400-2"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb400-2" aria-hidden="true" tabindex="-1"></a>p_wheat <span class="ot">=</span> wheat_blast <span class="sc">%&gt;%</span></span>
<span id="cb400-3"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb400-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>wetting_period, <span class="at">y=</span>intensity)) <span class="sc">+</span></span>
<span id="cb400-4"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb400-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color=</span><span class="st">&quot;blue&quot;</span>)</span>
<span id="cb400-5"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb400-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb400-6"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb400-6" aria-hidden="true" tabindex="-1"></a>p_wheat</span></code></pre></div>
<p><img src="data-science-for-agricultural-professionals_files/figure-html/unnamed-chunk-240-1.png" width="672" /></p>
<p>We fit the data with the logistic model.</p>
<div class="sourceCode" id="cb401"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb401-1"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb401-1" aria-hidden="true" tabindex="-1"></a>wheat_blast_model_logist <span class="ot">=</span> stats<span class="sc">::</span><span class="fu">nls</span>(intensity <span class="sc">~</span> <span class="fu">SSlogis</span>(wetting_period, Asym, xmid, scal), <span class="at">data=</span>wheat_blast)</span>
<span id="cb401-2"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb401-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(wheat_blast_model_logist)</span></code></pre></div>
<pre><code>## 
## Formula: intensity ~ SSlogis(wetting_period, Asym, xmid, scal)
## 
## Parameters:
##      Estimate Std. Error t value Pr(&gt;|t|)    
## Asym  0.83092    0.01606   51.74 3.50e-09 ***
## xmid 19.13425    0.33505   57.11 1.94e-09 ***
## scal  2.95761    0.28825   10.26 5.00e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.02552 on 6 degrees of freedom
## 
## Number of iterations to convergence: 1 
## Achieved convergence tolerance: 4.024e-06</code></pre>
<p>Convergence criteria was met. Here is the data plotted with the logistic model.</p>
<div class="sourceCode" id="cb403"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb403-1"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb403-1" aria-hidden="true" tabindex="-1"></a>test_data_wheat_log <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">wetting_period =</span> <span class="fu">seq</span>(<span class="dv">1</span>,<span class="dv">40</span>,<span class="dv">1</span>))</span>
<span id="cb403-2"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb403-2" aria-hidden="true" tabindex="-1"></a>test_data_wheat_log<span class="sc">$</span>pred <span class="ot">=</span> <span class="fu">predict</span>(wheat_blast_model_logist, test_data_wheat_log)</span>
<span id="cb403-3"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb403-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb403-4"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cb403-4" aria-hidden="true" tabindex="-1"></a>p_wheat <span class="sc">+</span> <span class="fu">geom_line</span>(<span class="at">data=</span>test_data_wheat_log, <span class="fu">aes</span>(<span class="at">x=</span>wetting_period, <span class="at">y=</span>pred), <span class="at">color=</span><span class="st">&quot;tomato&quot;</span>)</span></code></pre></div>
<p><img src="data-science-for-agricultural-professionals_files/figure-html/unnamed-chunk-242-1.png" width="672" /></p>
</div>
<div id="starting-variable-values" class="section level4" number="11.2.2.3">
<h4><span class="header-section-number">11.2.2.3</span> Starting Variable Values</h4>
<p>As mentioned earlier, nonlinear regression algorithms can be difficult to use in that they don’t fit a regression model using the least squares approach. Instead, nonlinear regression “nudges” the different coefficients in its equation until it zeros in on coefficient values that best fit the data. Often, traditionally, algorithms have not been able to solve for these coefficients from scratch. The user would have to provide initial coefficient values and hope they were close enough to true values that the nonlinear algorithm could then fit the curve.</p>
<p>What a pain in the butt. While some coefficients could be easily guessed, others required more complex calculations. With R, some packages have introduced “self-starting” non-linear models that do not require the user to enter initial values for coefficients. I have used those to create the examples above and we will cover them in the exercises. Just be aware, were you to get into more intensive nonlinear modelling, that you may need to specify those variables.</p>
</div>
</div>
</div>
<div id="summary-1" class="section level2" number="11.3">
<h2><span class="header-section-number">11.3</span> Summary</h2>
<p>Multivariate models (those that model yield or another response to multiple variables) are very powerful tools for unlocking the mysteries of how changes in environment drive what we observe in our research. However, they require skill to use. Remember that more variables do not automatically make a better model. Too many variables can cause our model to overfit our original data, but be less accurate or unbiased in fitting future datasets. Ask yourself whether it makes sense to include each variable in a model. Covariance matrixes and partial correlations can help us identify predictor variables that may be correlated with each other instead of the response variable.</p>
<p>Cross validation is also an important tool in assessing how a model will work with future data. In this unit, we learned a common practice, 10-fold cross validation, in which the data were divided into 10 groups. Each group took turns being part of the datasets used to train the model, and the dataset used to test it.</p>
<p>Finally, nonlinear regression is used to fit variables that have a nonlinear relationship. Untlike multiple linear regression, there is usually only one predictor variable in non-linear regression. In addition, nonlinear regression is often based on a theoretical relationship between the predictor and response variable. In this unit, we focused on two models: the monomolecular model for relationships between yield and soil fertility, and the logistic model for predicting growth of plants and other organisms.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="correlation-and-simple-regression.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="spatial-statistics.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/11-Multiple-Linear-and-Nonlinear-Regression.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["data-science-for-agricultural-professionals.pdf", "data-science-for-agricultural-professionals.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
